# Generated by Django 2.1.3 on 2019-07-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190705_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タグ')),
            ],
        ),
        migrations.AlterField(
            model_name='categoryofpost',
            name='name',
            field=models.CharField(max_length=30, verbose_name='カテゴリ名'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='posts.Tag', verbose_name='タグ'),
        ),
    ]
